---
title: "script notes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(magrittr)

viridis <- readRDS("../objects/viridis.rds")

```

## 1. Build a functionality to upload a data file 

This will only be needed locally as a temp and can be be reset when the session ends (therefore the file doesn't need to go through drop box)

Generate data for testing

```{r}
x = rep(1:100, 2) + rnorm(100*2, mean = 0, sd = 1)
b0 = 10
b1 = 2.4
sigma2 = x^2.3
residual = rnorm(x, mean = 0, sd = sqrt(sigma2))
y = b0 + b1*x + residual

robust_test_data <- 
  tibble::tibble(
    x = x, 
    y = y
  )
```


```{r}
lm(y ~ x, robust_test_data) %>% summary()
```

```{r}
robustbase::lmrob(y ~ x, robust_test_data) %>% summary()
```

```{r}
robust_test_data %<>% 
  dplyr::transmute(
    time = x, 
    insanity = y
  )
```

```{r}
# write.csv(robust_test_data, 
#           "../data/robust_test_data.csv", row.names = FALSE)
```

## Render model output 

```{r}
mod_1 <- lm(y ~ x, data = robust_test_data)
mod_2 <- robustbase::lmrob(y ~ x, data = robust_test_data)

model_output <- function(model) {
  
  summary(model)$coefficients %>% 
    as.data.frame() %>% 
    tibble::rownames_to_column() %>% 
    dplyr::rename(
      Coefficient = rowname
    )
  
}
```


```{r}
robust_test_data %<>% 
  tibble::rownames_to_column()
```

## Render plot 

get predicted values for plotting 

```{r}
pred_lm <- predict(mod_1, interval = "confidence") %>% 
  as.data.frame() %>% 
  tibble::rownames_to_column()

pred_lmrob <- predict(mod_2, interval = "confidence") %>% 
  as.data.frame() %>% 
  tibble::rownames_to_column()

robust_test_data %<>%
  dplyr::left_join(., pred_lm, by = "rowname") %>% 
  dplyr::left_join(., pred_lmrob, by = "rowname")

```


```{r}
ggplot2::ggplot(data = robust_test_data, aes(x = time, y = insanity)) + 
  geom_point(colour = viridis$blue_3, alpha = 0.5) + 
  geom_line(aes(y = fit.x), size = 1, colour = viridis$purple_1) + 
  geom_line(aes(y = fit.y), size = 1, colour = viridis$green_1) + 
  theme_minimal()
```

# Fitting models with multiple predictors

```{r}
multiple_pred <- robust_test_data %>% 
  dplyr::arrange(insanity) %>% 
  dplyr::mutate(
    dogs = sort(insanity, decreasing = TRUE) + rnorm(n = nrow(.), mean = 0, sd = 20), 
    course = c(rep("ba", 67), rep("msc", 67), rep("phd", 66))
  )
```

```{r}
#write.csv(multiple_pred, "../data/multiple_pred.csv", row.names = FALSE)
```


```{r}
lm(insanity ~ time + dogs + course + time:dogs, data = multiple_pred) %>% summary()

interaction = list("time", "dogs", "+", "+", "course", "insanity")
stringr::str_sub(interaction[length(interaction)], -1)
```

```{r}
interaction = list("time", "dogs", "+", "course", "insanity", "+", "course", "dogs")

int_string <- paste0(interaction, collapse = " ")
int_vector <- strsplit(int_string, " [+] ")[[1]] %>% 
  stringr::str_remove_all(., pattern = "[+][ +]")

add_double_colon <- function(x){
  stringr::str_replace_all(string = x, pattern = " ", replacement = ":")
}

purrr::map(.x = int_vector, .f = add_double_colon) %>% 
  paste0(., collapse = " + ")

```

```{r}
check_multi_plus <- function(interaction_input){
  
  check_multi_plus_tib <- 
    tibble::tibble(
      int_original = interaction %>% paste(), 
      int_lead = dplyr::lead(interaction) %>% paste(), 
      is_plus = dplyr::if_else(int_original == "+" & int_lead == "+", 1, 0)
    )
  
  any(check_multi_plus_tib$is_plus == 1)
  
}

check_multi_plus(interaction)
```

```{r}
process_int_string <- function(interaction_input){
  
  int_string = paste0(interaction_input, collapse = " ")
  
  int_vector = strsplit(int_string, " [+] ")[[1]] %>% 
    stringr::str_remove_all(., pattern = "[+][ +]")
  
  purrr::map(.x = int_vector, .f = add_double_colon) %>% 
    paste0(., collapse = " + ")
  
}
```

```{r}
rep(c("dog", "course", "+"), 4)

rep(c(names(rvs$data), "+"), times = rvs$n_interactions)
```

```{r}
predictor <- "time+dogs+"

stringr::str_sub(predictor[length(predictor)], -1) <- ""


penguins
```

```{r}
vec_1 <- c("a", "b", "c")
vec_2 <- vec_1[!vec_1 %in% "c"]
vec_2
```

